
version: 0.2

env:
  variables:
    STATE_BUCKET: "pipeline"
    LOCKDB_TABLE: "table"
    REV: "revision"
    IMAGE_NAME: "name"
    SSH_KEY: "key_name"

phases:
  install:
    commands:
      - echo Install Terraform
      - mv /inf/terraform /usr/local/bin/
      - echo Install Packer
      - mv /inf/packer /usr/local/bin/
  pre_build:
    commands:
      - echo Change directory and Validate Packer file
      - cd $REV/infrastructure/packer
      - packer validate build.pkr.hcl
      - echo Change directory, Init, and Validate Terraform
      - cd ../terraform
      - terraform init -backend-config="bucket=$STATE_BUCKET" -backend-config="dynamodb_table=$LOCKDB_TABLE"
      - terraform validate
  build:
    commands:
      - echo Change directory and run Packer to build AMI image
      - cd ../packer
      - packer build -var "image_name=$IMAGE_NAME" build.pkr.hcl
      - echo Change directory and Apply Terrafrom Infrastructure
      - cd ../terraform
      - terraform apply -var="image_name=$IMAGE_NAME" -var="ssh_key=$SSH_KEY" -auto-approve
  post_build:
    commands:
      - echo Check Terraform state for EC2 public DNS name
      - CHECKSITE=$(terraform output instance)
      - echo ping Docker website
