
version: 0.2

env:
  variables:
    STATE_BUCKET: "pipeline"
    LOCKDB_TABLE: "table"
    REV: "revision"
    IMAGE_NAME: "name"
    SSH_KEY: "key_name"

phases:
  install:
    commands:
      - echo Install Terraform
      - wget https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      - unzip terraform_0.12.28_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - echo Install Packer
      - wget https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip
      - unzip packer_1.6.0_linux_amd64.zip
      - mv packer /usr/local/bin/
  pre_build:
    commands:
      - echo Change directory and Validate Packer file
      - cd $REV/infrastructure/packer
      - packer validate build.pkr.hcl
  build:
    commands:
      - echo Change directory and run Packer to build AMI image
      - packer build -var "image_name=$IMAGE_NAME" build.pkr.hcl
      - echo Change directory and Run terraform init and apply to build Infrastructure
      - cd ../terraform
      - terraform init -backend-config="bucket=$STATE_BUCKET" -backend-config="dynamodb_table=$LOCKDB_TABLE"
      - terraform apply -var="image_name=$IMAGE_NAME" -var="ssh_key=$SSH_KEY" -auto-approve
  post_build:
    commands:
      - echo Check Terraform state for EC2 public DNS name
      - CHECKSITE=$(terraform output instance)
      - echo ping Docker website
